hash-format = "sha256"

[[files]]
file = "mods/ad-astra-giselle-addon.pw.toml"
hash = "2ee5a9e5a8cc755b428d953cc3f89a68c4f239136c50e9500ed62f13dd92561e"
metafile = true

[[files]]
file = "mods/ad-astra.pw.toml"
hash = "da42d2a6e6e3f7bd10df625ab23d6ba8a50ecb3545c1c3c6bda4f826caa5d51b"
metafile = true

[[files]]
file = "mods/aether.pw.toml"
hash = "6f87edf40bf0be7e7e266f9e2ff0bf7584c6bedff7975bad3259a21a60d1e598"
metafile = true

[[files]]
file = "mods/appleskin.pw.toml"
hash = "8d0321177fed4a0b48554c40158b43db62f6cdaa768f584ef6a11575dfaa6223"
metafile = true

[[files]]
file = "mods/applied-energistics-2.pw.toml"
hash = "0f4c2198603cd84a14dc6741729d0b0dcf509574776e620c36c3e7180082db32"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "5e9edd1fd2395f14a0c8a4acbdbdd61e1047be1f0033deb3140d2ce0d093e9d8"
metafile = true

[[files]]
file = "mods/ballistix.pw.toml"
hash = "60a9d6252ed7ba6f155517de0093e313677960b8f81c3a6d8fa7ab3d52e7918c"
metafile = true

[[files]]
file = "mods/balm.pw.toml"
hash = "f8b6ef08945410e1341212a2723477487fb66a2c8fd67dd201433658791d298d"
metafile = true

[[files]]
file = "mods/biomes-o-plenty.pw.toml"
hash = "83ba38ab1e5b583227e9d37b8fea91ac1fcb4e2f67ba86800c5d7aa4024d2993"
metafile = true

[[files]]
file = "mods/botarium.pw.toml"
hash = "008c942efc2e2ec221dd1a760b4a50e2f24ede37747731ba794f5e845554adcb"
metafile = true

[[files]]
file = "mods/building-wands.pw.toml"
hash = "c7955ddf99f02fe3a4203cedd586775fcf2d66e65fa2e9431ac358b9511de3c6"
metafile = true

[[files]]
file = "mods/cc-tweaked.pw.toml"
hash = "c45dce6b9e52796c0606ff222efa5833fd1d420fa67e7a8f26852196b80f6fa5"
metafile = true

[[files]]
file = "mods/chunk-loaders.pw.toml"
hash = "913bbc46f7ebbae12ee05efee5810b4c56a027336acc929951ee3bae1f084275"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "96204145e12506e0625d8b9bfa05aad54e9a62fd511bae39f0d57fcb5e39f4cc"
metafile = true

[[files]]
file = "mods/clumps.pw.toml"
hash = "e3173aaa4e9078ad7ace2b9ef43ce15ce9919c0b566d8830cea87264f92b3a6a"
metafile = true

[[files]]
file = "mods/codechicken-lib-1-8.pw.toml"
hash = "f88db7aef79947669ba4d736cc2f352a2269eb21770d5597d306c3017ea126dc"
metafile = true

[[files]]
file = "mods/cofh-core.pw.toml"
hash = "20fcd633516ef654e4a1546ab7e1cd4e22bc96a087544ae583f85df9b7a65468"
metafile = true

[[files]]
file = "mods/construction-wand.pw.toml"
hash = "1613f68b9bdd242a957a3a20c5193b640672d11087abcb5c3abe5da45b235e35"
metafile = true

[[files]]
file = "mods/controlling.pw.toml"
hash = "1e56f528d8e21b0cf9c52c3d6deea2a4eafa408170b39a070195dbf66617f373"
metafile = true

[[files]]
file = "mods/create-central-kitchen.pw.toml"
hash = "967c38265800a8b2353debf37ab919204a1f89e4a57e2e603b7a7de1d68c8956"
metafile = true

[[files]]
file = "mods/create-enchantment-industry.pw.toml"
hash = "200b30b8eeaaf2fa9e8345fcabdd80f6195b5af67926fb1e277931100e7e1eff"
metafile = true

[[files]]
file = "mods/create-steam-n-rails.pw.toml"
hash = "0971029a9e6cbc93c8fd694f97942c566979973f3d98023b730b1d436f617220"
metafile = true

[[files]]
file = "mods/create.pw.toml"
hash = "9d7971a7af2ff4a96a0e5aede76f9cf8dc978da601e2754f79d6ec8631125bb9"
metafile = true

[[files]]
file = "mods/createaddition.pw.toml"
hash = "8a5f33277995fccd2be6793c4fba1b5d657983be32f0b47e4afab4eac70b8ab8"
metafile = true

[[files]]
file = "mods/cucumber.pw.toml"
hash = "31b3ecd1317f2d2b9802592def351b5567196d726283530f72e33f5c827e5807"
metafile = true

[[files]]
file = "mods/curios.pw.toml"
hash = "1315cd56b0b4a5b3d53374cebf4f1f3cd0546b05058740847bd226c1d1ccab39"
metafile = true

[[files]]
file = "mods/electrodynamics.pw.toml"
hash = "b23ec970a5f2bd0a0873cc39225c7a5a1f3ec18e1c62b63c03b195718bb7c7cb"
metafile = true

[[files]]
file = "mods/embeddium.pw.toml"
hash = "a1575677daaaf6ea6dac12e5a10073e34025e5ca2c35b6d36ad4a5a0edbc0e82"
metafile = true

[[files]]
file = "mods/ender-io.pw.toml"
hash = "20408dc8b2d5965858fac965195ba1e7b4b3bf7da1bd9600d335fa1950924884"
metafile = true

[[files]]
file = "mods/ender-storage-1-8.pw.toml"
hash = "638f7c447dbe7dc2e85e4bf89d70fb41632db940a57de498094f2be57fa6c18d"
metafile = true

[[files]]
file = "mods/extreme-reactors.pw.toml"
hash = "fc21ff9cee2da4efc88692075c1f2ff648822808112dee3ca043f5ea5e9cdcd7"
metafile = true

[[files]]
file = "mods/farmers-delight.pw.toml"
hash = "067fc433511066d18b1795b86c9856246a8da7f9a4316afd6b25e5eee181f660"
metafile = true

[[files]]
file = "mods/fast-leaf-decay.pw.toml"
hash = "fd5aa059dd7e148e9ce801455b438425c0ad36537ce4b635edeb524900b15284"
metafile = true

[[files]]
file = "mods/ferritecore.pw.toml"
hash = "5bd0506bc0be25116b234f2b5af9447f60d82ae1cb6c5be4e12d8841f6c2501c"
metafile = true

[[files]]
file = "mods/flux-networks.pw.toml"
hash = "de63df967225278681e18afe0e323110322ec02006746980fbe77dbd974b20b3"
metafile = true

[[files]]
file = "mods/forgified-fabric-api.pw.toml"
hash = "62ef7e92478035b77e996189984e4749b2d876ed0a389977a2670a28f105bfd2"
metafile = true

[[files]]
file = "mods/framework.pw.toml"
hash = "376f8a190f00bd120193d7a665ebe1b03dfe329cc395f7d944f7216c1182c84d"
metafile = true

[[files]]
file = "mods/ftb-backups-2.pw.toml"
hash = "b3693e7a5647d4e28fc30ad3e85193c668a98a410dc3f425f19561cfea68957f"
metafile = true

[[files]]
file = "mods/ftb-library-forge.pw.toml"
hash = "48e2fa3089beed20a23ff2d171259768b2080ab0ff196841a18eb93c38e1c8b2"
metafile = true

[[files]]
file = "mods/ftb-ultimine-forge.pw.toml"
hash = "1c383e66311b5edd6d7116ae0544108d60450f58e94853126665d75d85561d68"
metafile = true

[[files]]
file = "mods/geckolib.pw.toml"
hash = "88f142bda6bfa6aff4f4d4e12b8ba7581aa40e3f163039a533f09dd6d634e093"
metafile = true

[[files]]
file = "mods/glitchcore.pw.toml"
hash = "c46659c3e873e0ca121f5215991ae8bc989132a3fea0c2da9eed0f22a947b2b9"
metafile = true

[[files]]
file = "mods/gravestone-mod.pw.toml"
hash = "df07d5af0d287b944943b65e0b0990dc21fbbad6fee05b9d698a9f62b906ea9c"
metafile = true

[[files]]
file = "mods/guideme.pw.toml"
hash = "5cc92eb0e58c2afbfd625d727d80da1d1c84500ec962bb22f5be28b864f18551"
metafile = true

[[files]]
file = "mods/hostile-neural-networks.pw.toml"
hash = "d8f52c6109108160c9ca80ae2d1fd03f3b27f4a3196c62ba805928b66482be5b"
metafile = true

[[files]]
file = "mods/immersive-engineering.pw.toml"
hash = "6439c6f409308c4a89a12708b54cef41aa5382dc78e6f352b3e8005e96a21a8e"
metafile = true

[[files]]
file = "mods/industrial-foregoing.pw.toml"
hash = "762fded46cec5b2f224483c9fac2248184d8b88144556021be75a7f3c05c2da8"
metafile = true

[[files]]
file = "mods/iron-jetpacks.pw.toml"
hash = "c3265a04984be048307745587dab58deb0466efd99a40d335f23696fb4f9947e"
metafile = true

[[files]]
file = "mods/jade.pw.toml"
hash = "8f359d190506a6f824763b8e7c390d9e22204ef11e3ffa5ef980000d17e2c2b6"
metafile = true

[[files]]
file = "mods/jei.pw.toml"
hash = "29b62d42548542296d9932bcbb8a93ffba0b75b7cc859a67e596aeb1e048ace2"
metafile = true

[[files]]
file = "mods/just-enough-guns.pw.toml"
hash = "6c01c4e336f958358365b1aad494760260785101d0904cc46e2c3f0e2a6d4208"
metafile = true

[[files]]
file = "mods/just-enough-resources-jer.pw.toml"
hash = "2f4dd47f2ac99a55c332638116596bbdc38a06ac86336bb662e42c604c3a96e6"
metafile = true

[[files]]
file = "mods/laserio.pw.toml"
hash = "9d85a210e77661032cfbcd930059096be6cfb6afd9abedde21bcdfa4e5b25e54"
metafile = true

[[files]]
file = "mods/lendercataclysm.pw.toml"
hash = "75199fa3b762c5aa781e3cb2aab7779d19128b2a1c5b15798d5e613df8d16573"
metafile = true

[[files]]
file = "mods/lionfish-api.pw.toml"
hash = "60af8798dbf3e300a5af44125595afcd5d1e70072448444156364f222cc03e98"
metafile = true

[[files]]
file = "mods/macaws-bridges.pw.toml"
hash = "48b6be3ef711114f233e0c36d7f625b1e42c247c3e78a51fd7498886657a2384"
metafile = true

[[files]]
file = "mods/macaws-doors.pw.toml"
hash = "33af5f73cc7b802cf45b02ef7ec7b9a516919d55ed32a035a4661f33331b5531"
metafile = true

[[files]]
file = "mods/mcjtylib.pw.toml"
hash = "ff60c101d23ba31406049f45f8a7d77172287e1b9927ad2b5335eb31ff4c2cb2"
metafile = true

[[files]]
file = "mods/mekanism.pw.toml"
hash = "7c411a566d022680769ddb8323984fff292ddeb35e7d8fcfe2cc41b9885d9557"
metafile = true

[[files]]
file = "mods/mob-grinding-utils.pw.toml"
hash = "22ffca942573f1c39cc6c495122a31706a12eeb655c013c6c017aa1306ccaf7b"
metafile = true

[[files]]
file = "mods/modernfix.pw.toml"
hash = "11cd7da81a933aab04f091e2c25447b6d11ebe98bfeed244426a86dd31f3df04"
metafile = true

[[files]]
file = "mods/mouse-tweaks.pw.toml"
hash = "e72f73611904e14d915418f0e3c6cb483cdc600e211375c2eceb393fec5b80f1"
metafile = true

[[files]]
file = "mods/mowzies-mobs.pw.toml"
hash = "6ff4dfc30b3df634c6a2e587742ad381aa5988a50a646003369331749882c0a9"
metafile = true

[[files]]
file = "mods/neruina.pw.toml"
hash = "4c0251ac6bb2f84ae540ddd3c5619fa1d126ca6f55679ed898a1cdf0f5932135"
metafile = true

[[files]]
file = "mods/nuclear-science.pw.toml"
hash = "e8129b596fa562e94359b6d293a6e4eaea86a96924658f75647ba1741f53c486"
metafile = true

[[files]]
file = "mods/oculus.pw.toml"
hash = "200f79b635a087841698c85ac7028f0a1fac2cc4ffae1d59ff3f07a94abfe70e"
metafile = true

[[files]]
file = "mods/openblocks-elevator.pw.toml"
hash = "51bf17db22eee5fb80da0b2efe87b846f1165bafc67a789782c5fd976c406ffa"
metafile = true

[[files]]
file = "mods/patchouli.pw.toml"
hash = "dec2bc011d4ca1d451aaa3eea477f13366bfb13beba0716018f47d9331a50d8e"
metafile = true

[[files]]
file = "mods/placebo.pw.toml"
hash = "045d582e2c534c5bb96d7336b4ae2cd12692c6de29b19ae5f1dbfd8759c03b03"
metafile = true

[[files]]
file = "mods/polylib.pw.toml"
hash = "947d5f3b9213360b68e9b65a8d2d5111939e82e248cf61eb02137f119c6eaeb6"
metafile = true

[[files]]
file = "mods/polymorph.pw.toml"
hash = "8c65958007f81cdf1a57dac999ec7ffdde17cce6154c9a2f75bbb389fd11efbf"
metafile = true

[[files]]
file = "mods/resourceful-config.pw.toml"
hash = "e242387207a2538b5ccb55697174c65e549e1eb2fef9da37e1ad3734e0372b65"
metafile = true

[[files]]
file = "mods/resourceful-lib.pw.toml"
hash = "ef0264b7d819848f72ab2f34643306187e712965a8246e1f733e1bd39d8fd681"
metafile = true

[[files]]
file = "mods/rftools-base.pw.toml"
hash = "9b51ec1408e4831a769779c1363a80d818d88554981ee369d06da30c2523db50"
metafile = true

[[files]]
file = "mods/searchables.pw.toml"
hash = "2cb8dd9a3944a6430b49916a4fe1b6cf0bd7efd907054f8e679a02717149404f"
metafile = true

[[files]]
file = "mods/security-craft.pw.toml"
hash = "0a9437e4b4d53291137e780a5f4d85dc06f584b1c43b8fdec788158da1770f3e"
metafile = true

[[files]]
file = "mods/sinytra-connector.pw.toml"
hash = "6db079b4b12f1b14243980080879cc40087c3507f3ad25adf97e5f0ce9bb163b"
metafile = true

[[files]]
file = "mods/sophisticated-backpacks.pw.toml"
hash = "d820ddc633c3844bd8f4e4eb2401ee8d0b2a9cc9713338045d09502e609f2b62"
metafile = true

[[files]]
file = "mods/sophisticated-core.pw.toml"
hash = "69dd7341ad086e0fa23bef3ba04237c4c74ea76800cf8289050b09eda3268c5c"
metafile = true

[[files]]
file = "mods/spark.pw.toml"
hash = "d0e1a79dbcda8499e0f12f4adaa5503f9bbc84a6274ce07b3a3839476622e8e5"
metafile = true

[[files]]
file = "mods/storage-drawers.pw.toml"
hash = "371b68e257eaca322ca4e95f4aa8d95441d84110b69243dda818f743a0111ba5"
metafile = true

[[files]]
file = "mods/supermartijn642s-config-lib.pw.toml"
hash = "3eede8a7ebafb69840153ff51dbc879b0232799e90a834ab6d71274b1316179f"
metafile = true

[[files]]
file = "mods/supermartijn642s-core-lib.pw.toml"
hash = "76e4681bea67f97c8cd0b14c289cf1fbc71a6b475929fafc4132040becdc9047"
metafile = true

[[files]]
file = "mods/terrablender.pw.toml"
hash = "fde3d3b1607636100e382dce1bba80ab4608ebfa1ef888a37b86bc8c7dcbafe5"
metafile = true

[[files]]
file = "mods/the-zoomify-mod.pw.toml"
hash = "b75a777a1f65a833e5398800f3fe2715b0828989d366c38eca724c0269e233be"
metafile = true

[[files]]
file = "mods/thermal-expansion.pw.toml"
hash = "1603a2d57a71762925e57c61ae45649bf6aab128295a31efec214b0676c79024"
metafile = true

[[files]]
file = "mods/thermal-foundation.pw.toml"
hash = "626f0ea226f55c453930ef387b32ad090c8defdd07792fe0aefc4b5afa87cb46"
metafile = true

[[files]]
file = "mods/titanium.pw.toml"
hash = "5e41fd8f565e09e83868e4c4776154befd3203b01ed5f09b6f7cd27687ec0041"
metafile = true

[[files]]
file = "mods/voltaic-api.pw.toml"
hash = "e2a0d097e297d8c881178291f716655cfe604d7412ab083fc5ac401da9d3a130"
metafile = true

[[files]]
file = "mods/waystones.pw.toml"
hash = "5dbc1ed70c1dd5c99c93d353b6267c6a4e7af2b342d0ad4ddecf54593e199224"
metafile = true

[[files]]
file = "mods/xaeros-minimap.pw.toml"
hash = "89f2e05f2ca0bea0df3374cb7b3d862f9209a01d7325e69c5eb98f0218594d47"
metafile = true

[[files]]
file = "mods/xaeros-world-map.pw.toml"
hash = "42d13af643345d229b9d3a08b5e2a25d8fb1ce8ebead2b3431a70346ca652e94"
metafile = true

[[files]]
file = "mods/xnet.pw.toml"
hash = "aa7f10fc9d64f50c305e1b74d9e6718f7b9dad7a61afe912e794cd0247f6228d"
metafile = true

[[files]]
file = "mods/zerocore.pw.toml"
hash = "648294f08f565cae9bd37855662a3a02404684d9043eb333d097e992d9519b4b"
metafile = true

[[files]]
file = "resourcepacks/fresh-animations.pw.toml"
hash = "64f90fd9619a092a8a5493d6ad9605bc5fec13f50f02feef1dcf47c9496a80bd"
metafile = true

[[files]]
file = "shaderpacks/rethinking-voxels.pw.toml"
hash = "0a3f01f56afd065dc65dffb073b4fc5f9ae031aaef08d95d9df92e0093ac8504"
metafile = true
