name = "2026 Minecraft Server"
author = "unluckyGolem"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8e1dc8317f30a90ead9e25baf955b7f38b69874cf3345c8bff583da80a131bfc"

[versions]
forge = "47.4.13"
minecraft = "1.20.1"
