name = "2026 Minecraft Server"
author = "unluckyGolem"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "87c54071a46dce5623b9b8a5f125eff84d597ecf6029390a006019bd2a0e504d"

[versions]
forge = "47.4.13"
minecraft = "1.20.1"
